---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Exercises on interfacing ODK with R

<!-- badges: start -->
<!-- badges: end -->

This is a template repository for exercises designed to teach and practice interfacing [ODK](https://getodk.org) with [R](https://cran.r-project.org). This template repository can be used within a [GitHub Classroom](https://classroom.github.com) environment.

## Exercises

This repository currently includes the following exercises:

### Exercise 1: Install odkr and okapi packages in R

This exercise is the most basic and simplest. Install the odkr and okapi packages in your [R](https://cran.r-project.org) installation in your own local machines.

Starter code for this exercise is named `exercise_1_install_packages.R`.

### Exercise 2: Retrieving data from ONA using odkr package

This exercise is for retreiving data from ONA using the odkr package. You now have access to a testing ONA server with the account name validtrial with a form called Test Server. You can access this account using your own ONA account. Using this and using the documentation available from the odkr package (see https://github.com/rapidsurveys/odkr), show R code that will retrieve the data from the Test Server form.

Starter code for this exercise is named `exercise_2_retrieve_odkr.R`.

### Exercise 3: Retrieving data from ONA using okapi package

This exercise is for retreiving data from ONA using the okapi package. You now have access to a testing ONA server with the account name validtrial with a form called Test Server. You can access this account using your own ONA account. Using this and using the documentation available from the okapi package (see https://github.com/rapidsurveys/okapi), show R code that will retrieve the data from the Test Server form.

Starter code for this exercise is named `exercise_3_retrieve_okapi.R`.

